import { Template } from './types';

export const templates: Template[] = [
  {
    id: 1,
    name: 'Golden Elegance',
    category: 'elegant',
    gradient: ['#FFD700', '#FFA500', '#FF8C00'],
    pattern: 'radial',
    textColor: '#FFFFFF',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 2,
    name: 'Royal Purple',
    category: 'elegant',
    gradient: ['#4A148C', '#7B1FA2', '#9C27B0'],
    pattern: 'diagonal',
    textColor: '#FFD700',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 3,
    name: 'Ocean Dreams',
    category: 'modern',
    gradient: ['#006994', '#0099CC', '#33B5E5'],
    pattern: 'wave',
    textColor: '#FFFFFF',
    titleSize: '5xl',
    subtitleSize: '2xl',
  },
  {
    id: 4,
    name: 'Sunset Paradise',
    category: 'modern',
    gradient: ['#FF6B6B', '#FF8E53', '#FFB347'],
    pattern: 'circular',
    textColor: '#FFFFFF',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 5,
    name: 'Emerald Luxury',
    category: 'elegant',
    gradient: ['#065F46', '#059669', '#10B981'],
    pattern: 'geometric',
    textColor: '#FFD700',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 6,
    name: 'Rose Gold Premium',
    category: 'elegant',
    gradient: ['#B76E79', '#E8B4B8', '#FFC1CC'],
    pattern: 'floral',
    textColor: '#8B4513',
    titleSize: '5xl',
    subtitleSize: '2xl',
  },
  {
    id: 7,
    name: 'Islamic Crescent',
    category: 'islamic',
    gradient: ['#1E3A8A', '#3B82F6', '#60A5FA'],
    pattern: 'islamic',
    textColor: '#FFD700',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 8,
    name: 'Ramadan Nights',
    category: 'islamic',
    gradient: ['#1F2937', '#374151', '#4B5563'],
    pattern: 'stars',
    textColor: '#FBBF24',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 9,
    name: 'Festive Joy',
    category: 'festive',
    gradient: ['#DC2626', '#EF4444', '#F87171'],
    pattern: 'confetti',
    textColor: '#FFFFFF',
    titleSize: '5xl',
    subtitleSize: '2xl',
  },
  {
    id: 10,
    name: 'Birthday Blast',
    category: 'festive',
    gradient: ['#7C3AED', '#8B5CF6', '#A78BFA'],
    pattern: 'balloons',
    textColor: '#FFFFFF',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 11,
    name: 'Midnight Magic',
    category: 'modern',
    gradient: ['#000000', '#1E1E1E', '#3A3A3A'],
    pattern: 'sparkle',
    textColor: '#FFD700',
    titleSize: '5xl',
    subtitleSize: '2xl',
  },
  {
    id: 12,
    name: 'Coral Reef',
    category: 'modern',
    gradient: ['#FF6F61', '#FF8F7C', '#FFAF98'],
    pattern: 'organic',
    textColor: '#FFFFFF',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 13,
    name: 'Mint Fresh',
    category: 'modern',
    gradient: ['#00D9C0', '#00E5CC', '#00F2D8'],
    pattern: 'bubbles',
    textColor: '#1F2937',
    titleSize: '5xl',
    subtitleSize: '2xl',
  },
  {
    id: 14,
    name: 'Sapphire Nights',
    category: 'elegant',
    gradient: ['#1E40AF', '#3B82F6', '#60A5FA'],
    pattern: 'crystalline',
    textColor: '#FFFFFF',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
  {
    id: 15,
    name: 'Champagne Celebration',
    category: 'elegant',
    gradient: ['#F4E4C1', '#E6D5A8', '#D4C18D'],
    pattern: 'luxury',
    textColor: '#8B4513',
    titleSize: '4xl',
    subtitleSize: 'xl',
  },
];
